import json

companies = [
    {"name": "Razorpay", "ats": "greenhouse", "token": "razorpay"},
    {"name": "Swiggy", "ats": "greenhouse", "token": "swiggy"},
    {"name": "CRED", "ats": "greenhouse", "token": "cred"},
    {"name": "PhonePe", "ats": "greenhouse", "token": "phonepe"},
    {"name": "Meesho", "ats": "lever", "token": "meesho"},
    {"name": "Zepto", "ats": "lever", "token": "zepto"},
    {"name": "Ola", "ats": "greenhouse", "token": "ola"},
    {"name": "CureFit", "ats": "greenhouse", "token": "curefit"},
    {"name": "ShareChat", "ats": "greenhouse", "token": "sharechat"},
    {"name": "Khatabook", "ats": "lever", "token": "khatabook"},
    {"name": "Unacademy", "ats": "lever", "token": "unacademy"},
    {"name": "BharatPe", "ats": "greenhouse", "token": "bharatpe"},
    {"name": "Zerodha", "ats": "lever", "token": "zerodha"},
    {"name": "Postman", "ats": "greenhouse", "token": "postman"},
    {"name": "BrowserStack", "ats": "greenhouse", "token": "browserstack"},
    {"name": "Gojek", "ats": "greenhouse", "token": "gojek"},
    {"name": "Rippling", "ats": "greenhouse", "token": "rippling"},
    {"name": "Deel", "ats": "lever", "token": "deel"},
    {"name": "Navi", "ats": "greenhouse", "token": "navi"},
    {"name": "Groww", "ats": "greenhouse", "token": "groww"},
    {"name": "CoinSwitch", "ats": "lever", "token": "coinswitch"},
    {"name": "CoinDCX", "ats": "lever", "token": "coindcx"},
    {"name": "Dream11", "ats": "greenhouse", "token": "dream11"},
    {"name": "InMobi", "ats": "greenhouse", "token": "inmobi"},
    {"name": "Cars24", "ats": "greenhouse", "token": "cars24"},
    {"name": "Spinny", "ats": "lever", "token": "spinny"},
    {"name": "Upstox", "ats": "greenhouse", "token": "upstox"},
    {"name": "Blinkit", "ats": "greenhouse", "token": "blinkit"},
    {"name": "Ather Energy", "ats": "greenhouse", "token": "atherenergy"},
    {"name": "Urban Company", "ats": "lever", "token": "urbancompany"},
    {"name": "Paytm", "ats": "lever", "token": "paytm"},
    {"name": "Pine Labs", "ats": "greenhouse", "token": "pinelabs"},
    {"name": "Licious", "ats": "greenhouse", "token": "licious"},
    {"name": "Pharmeasy", "ats": "lever", "token": "pharmeasy"},
    {"name": "Cleartax", "ats": "greenhouse", "token": "cleartax"},
    {"name": "Chargebee", "ats": "greenhouse", "token": "chargebee"},
    {"name": "MindTickle", "ats": "greenhouse", "token": "mindtickle"},
    {"name": "Innovaccer", "ats": "greenhouse", "token": "innovaccer"},
    {"name": "Druva", "ats": "greenhouse", "token": "druva"},
    {"name": "HighRadius", "ats": "greenhouse", "token": "highradius"},
    {"name": "Icertis", "ats": "greenhouse", "token": "icertis"},
    {"name": "Zenoti", "ats": "greenhouse", "token": "zenoti"},
    {"name": "Hasura", "ats": "lever", "token": "hasura"},
    {"name": "Vercel", "ats": "greenhouse", "token": "vercel"},
    {"name": "MongoDB", "ats": "greenhouse", "token": "mongodb"},
    {"name": "Atlassian", "ats": "greenhouse", "token": "atlassian"},
    {"name": "Uber", "ats": "greenhouse", "token": "uber"},
    {"name": "Discord", "ats": "greenhouse", "token": "discord"},
    {"name": "Airbnb", "ats": "greenhouse", "token": "airbnb"},
    {"name": "Stripe", "ats": "greenhouse", "token": "stripe"}
]

with open("india_tech_companies.json", "w") as f:
    json.dump(companies, f, indent=4)

print("Generated india_tech_companies.json with 50 companies.")
